name: clone_private_repo

#on: [workflow_dispatch, push]
on: [workflow_dispatch]
jobs:
  clonepvtrepo:
    runs-on: self-hosted
    steps:
    #- name: Clone sundar-aerlync/Test-aerlync
    #  uses: sundar-aerlync/clone-github-repo-action@v2.3
    - name: Git Tests
      run: |
        git clone https:/x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/sundar-aerlync/Test-aerlync.git
