name: clone_private_repo

#on: [workflow_dispatch, push]
on: [workflow_dispatch]
jobs:
  clonepvtrepo:
    runs-on: self-hosted
    steps:           
    - name: Git Tests
      uses: srinivasa-aerlync/clone-github-repo-action@v2.3
      with:
       owner: 'srinivasa-aerlync'
       repository: 'Test-aerlync'
       access-token: ${{ secrets.ACCESS_TOKEN }}
      #run: |
      #  git clone https://${GITHUB_TOKEN}:x-oauth-basic@github.com/srinivasa-aerlync/Test-aerlync.git
