name: clone_private_repo

#on: [workflow_dispatch, push]
on: [workflow_dispatch]
jobs:
  clonepvtrepo:
    runs-on: self-hosted
    steps:           
    - name: Git Tests
      uses: actions/checkout@v3
      with:
       repository: srinivasa-aerlync/Test-aerlync
       token: ${{ secrets.TOKEN }}
       ref: 'main'
       path: master
      env:
        PAT_TOKEN: ${{ secrets.TOKEN }}
        run: |
         git clone https://PAT_TOKEN@github.com/srinivasa-aerlync/Test-aerlync.git
