name: clone_private_repo

#on: [workflow_dispatch, push]
on: [workflow_dispatch]
jobs:
  clonepvtrepo:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Git Tests
      run: |
        git clone https://@github.com/sundar-aerlync/Test-aerlync.git
