name: clone_private_repo

#on: [workflow_dispatch, push]
on: [workflow_dispatch]
jobs:
  clonepvtrepo:
    runs-on: self-hosted
    steps:           
    - name: Git Tests
      uses: actions/checkout@master
      with:
       repository: 'srinivasa-aerlync/Test-aerlync'
       token: ${{ secrets.TOKEN }}
       #access-token: ${{ secrets.TOKEN }}
      #run: |
      #  git clone https://${GITHUB_TOKEN}:x-oauth-basic@github.com/srinivasa-aerlync/Test-aerlync.git
