name: clone_private_repo

#on: [workflow_dispatch, push]
on: [workflow_dispatch]
jobs:
  clonepvtrepo:
    runs-on: self-hosted
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3
      with:
          # Use the GitHub token to clone the repository
          token: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Git Tests
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git clone https://github.com/srinivasa-aerlync/Test-aerlync.git
