name: clone_private_repo

#on: [workflow_dispatch, push]
on: [workflow_dispatch]
jobs:
  clonepvtrepo:
    runs-on: self-hosted
    steps:
    - name: Git Tests
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git clone https://github.com/srinivasa-aerlync/Test-aerlync.git
