name: clone_private_repo

#on: [workflow_dispatch, push]
on: [workflow_dispatch]
permissions:
  contents: write
jobs:
  clonepvtrepo:
    runs-on: self-hosted
    steps:           
    - name: Git Tests
      uses: actions/checkout@v3
      with:       
       token: ${{ secrets.mytoken }}
       repository: srinivasa-aerlync/Test-aerlync
       ref: main
       path: master
      env:
        PAT_TOKEN: ${{ secrets.mytoken }}
        run: |
         git clone https://srinivasa-aerlync:${ PAT_TOKEN }@github.com/srinivasa-aerlync/Test-aerlync.git
