name: Python script run

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python environment
      run: |
        source ~/zephyrproject/.venv/bin/activate

    - name: Run Python script
      run: python your_script.py
