name: Zephyr samples python script
on: [workflow_dispatch, push]
jobs:
  usevenv:
    runs-on: self-hosted
    steps:
    - name: Utilizing the self-hosted machine zephyr venv
      id: zephyr Python venv
    - run: export ZEPHYR_BASE=$PWD
    - run: source zephyr-env.sh
    - run: ls -la
    - run: pwd
    - run: source ~/zephyrproject/.venv/bin/activate
    - run: echo source ~/zephyrproject/.venv/bin/activate
    #- name: zephyr tool_chain
    #  env:
    #    ZEPHYR_BASE: /home/aerlync/zephyrproject
    #    ZEPHYR_TOOLCHAIN_VARIANT: zephyr
    #- run: echo "Run build_helpers tests"  
    #- run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
