name: Zephyr samples python script
on: [push]
jobs:
  usevenv:
    runs-on: self-hosted
    steps:
    - name: Utilizing the self-hosted machine zephyr venv
      id: zephyr Python venv
      env:
        run: |
         export ZEPHYR_BASE=$PWD
         source zephyr-env.sh
         # debug
         ls -la
         pwd
         source ~/zephyrproject/.venv/bin/activate
         echo source ~/zephyrproject/.venv/bin/activate
    - name: zephyr tool_chain
    env:
        ZEPHYR_BASE: /home/aerlync/zephyrproject
        ZEPHYR_TOOLCHAIN_VARIANT: zephyr
        run: |
           echo "Run build_helpers tests"
           
