name: Python venv
run-name: ${{ github.actor }} is testing penv
on: [workflow_dispatch, push]
jobs:
  utilizing_python_venv:
    name: job 1 - python venv
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          README.md
        sparse-checkout-cone-mode: false
    - name: Utilizing the self-hosted machine zephyr venv
      id: zephyr Python venv
    - run: echo Hello Srinivasa, this is Python env run
    - run: export ZEPHYR_BASE=$PWD
    - run: source zephyr-env.sh
    - run: ls -la
    - run: pwd
    - run: source ~/zephyrproject/.venv/bin/activate
    - run: echo source ~/zephyrproject/.venv/bin/activate
    #- name: zephyr tool_chain
    #  env:
    #    ZEPHYR_BASE: /home/aerlync/zephyrproject
    #    ZEPHYR_TOOLCHAIN_VARIANT: zephyr
    #- run: echo "Run build_helpers tests"  
    #- run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
