name: Python venv
on: [workflow_dispatch, push]
jobs:
  utilizing_python_venv:
    name: job 1 - python venv
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          README.rst
        sparse-checkout-cone-mode: false
    - name: Display the path
      run: |
        import os
        echo $(os.environ['PATH'])
      shell: python
    - name: Utilizing the self-hosted machine zephyr venv
      id: zephyr Python venv
      run: echo "Hello Srinivasa, this is Python env run"
    - name: Set ZEPHYR_BASE
      run: echo "ZEPHYR_BASE=$PWD" >> $GITHUB_ENV
    - name: Source zephyr-env.sh
      run: source zephyr-env.sh
    - name: List files
      run: ls -la
    - name: Print working directory
      run: pwd
    - name: Activate Python venv
      run: source ~/zephyrproject/.venv/bin/activate
    - name: Echo Python venv activation command
      run: echo "source ~/zephyrproject/.venv/bin/activate"
