name: Zephyr enviornment creation

on: [workflow_dispatch, push]

jobs:
  Zephyrenviornmentcreation:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set date variable
      id: set_date
      run: echo "TODAY_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends git ninja-build gperf ccache dfu-util device-tree-compiler wget python3-pip python3-setuptools python3-wheel xz-utils file make gcc gcc-multilib g++-multilib libsdl2-dev

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.12
        
    - name: Setup Zephyr environment
      run: |
        pip3 install west
        west init -m git@github.com:Atmosic/apps 
        west update
        west zephyr-export
        pip3 install -r zephyr/scripts/requirements.txt
        pip3 install cryptography

    - name: Build Zephyr sample
      run: |
        export ZEPHYR_SDK_INSTALL_DIR=/home/aerlync/zephyr-sdk-0.16.4
        source zephyr/zephyr-env.sh
        
        #west build -p auto -b ATMEVK-3330-QN-5 zephyr/samples/hello_world
        
        #Bluetooth beacon
        boards/arm/atm33evk/support/run.sh -e -b -w LL -a samples/bluetooth/beacon -j -s 900028963 ATMEVK-3330-QN-5
        tar -cvf bluetooth_beacon_sample_ATM33_${TODAY_DATE}.tar build/
        mv -f bluetooth_beacon_sample_ATM33_${TODAY_DATE}.tar /home/aerlync/archieve/
        
        #blinky_pwm
        boards/arm/atm33evk/support/run.sh -e -b -w LL -a samples/basic/blinky_pwm -j -s 900028963 ATMEVK-3330-QN-5
        tar -cvf blinky_pwm_sample_ATM33_${TODAY_DATE}.tar build/
        mv -f blinky_pwm_sample_ATM33_${TODAY_DATE}.tar /home/aerlync/archieve/
        
        #PWM
        boards/arm/atm33evk/support/run.sh -e -b -w LL -a tests/drivers/pwm/pwm_api -j -s 900028963 ATMEVK-3330-QN-5
        tar -cvf pwm_api_sample_ATM33_${TODAY_DATE}.tar build/
        mv -f pwm_api_sample_ATM33_${TODAY_DATE}.tar /home/aerlync/archieve/
        
        #I2C
        boards/arm/atm33evk/support/run.sh -e -b -w LL -a samples/sensor/lis2dh -j -s 900028963 ATMEVK-3330-QN-5
        tar -cvf i2c_sample_ATM33_${TODAY_DATE}.tar build/
        mv -f i2c_sample_ATM33_${TODAY_DATE}.tar /home/aerlync/archieve/
        
        #SPI
        boards/arm/atm33evk/support/run.sh -e -b -w LL -a samples/sensor/bme280 -j -s 900028963 ATMEVK-3330-QN-5
        tar -cvf spi_bme280_sample_ATM33_${TODAY_DATE}.tar build/
        mv -f spi_bme280_sample_ATM33_${TODAY_DATE}.tar /home/aerlync/archieve/
        
        #hello_world
        #zephyr/boards/arm/atm33evk/support/run.sh -e -b -w LL -a zephyr/samples/hello_world -j -s 900028963 ATMEVK-3330-QN-5
        #tar -cvf hello_world_sample_ATM33_${TODAY_DATE}.tar build/
        #mv -f hello_world_sample_ATM33_${TODAY_DATE}.tar /home/aerlync/archieve/
        
    #- name: Archive build artifacts
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: build-artifacts
    #    path: build/
