name: Zephyr enviornment creation

on: [workflow_dispatch, push]

jobs:
  Zephyrenviornmentcreation:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      #working-directory: zephyr
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends git ninja-build gperf ccache dfu-util device-tree-compiler wget python3-pip python3-setuptools python3-wheel xz-utils file make gcc gcc-multilib g++-multilib libsdl2-dev

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.12

    #- name: Create virtual environment
    #  #working-directory: zephy
    #  run: python3 -m venv zephyr/.venv

    #- name: Activate virtual environment
    #  run: |
    #      source zephyr/venv/bin/activate
          
    - name: Setup Zephyr environment
      #working-directory: zephyr
      run: |
        pip3 install west
        west init -m git@github.com:Atmosic/apps 
        #west init -l zephyr/
        #cd zephyr
        west update
        west zephyr-export
        pip3 install -r zephyr/scripts/requirements.txt
        pip3 install cryptography

    - name: Build Zephyr sample
      run: |
        export ZEPHYR_SDK_INSTALL_DIR=/home/aerlync/zephyr-sdk-0.16.4
        source zephyr/zephyr-env.sh
        #west build -p auto -b ATMEVK-3330-QN-5 zephyr/samples/hello_world
        zephyr/boards/arm/atm33evk/support/run.sh -e -d -w LL -a zephyr/samples/hello_world -j -s 900028963 ATMEVK-3330-QN-5

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build/zephyr/
