name: Zephyr(west) flash and run python test scripts
on: [workflow_dispatch, push]
jobs:
  Zephyrflashandrunscript:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Flash zephyr sample
      env:
        ZEPHYR_BASE: ~/zephyr
        ZEPHYR_TOOLCHAIN_VARIANT: zephyr
    #- run: cd ~/zephyr
    - run: ls -lart
    - run: pwd
    - run: source ~/zephyr/.venv/bin/activate
    - run: echo source ~/zephyr/.venv/bin/activate      
    - run: echo "Flash sample"
    - run: west flash --verify --device=900036560 --skip-rebuild -d build/ATMEVK-3330-QN-5_ns/zephyr/samples/hello_world --use-elf --elf-file build/ATMEVK-3330-QN-5_ns/zephyr/samples/hello_world/zephyr/zephyr.elf --bin-file build/ATMEVK-3330-QN-5_ns/zephyr/samples/hello_world/zephyr/zephyr.signed.bin --jlink
        
    - name: Initiate Python run
    - run: source ~/zephyr/.venv/bin/activate
    - run:  pytest  -v -s ~/zephyr/Aerlync/Tests/BLE --alluredir allure-results
       
