name: Zephyr hello world build flash & run hello_world

#on: [workflow_dispatch, push]
on: [workflow_dispatch]

jobs:
  Zephyrenviornmentcreation:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set date variable
      id: set_date
      run: echo "TODAY_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.12
        
    - name: Setup Zephyr environment
      run: |
        pip3 install west
        west init -m git@github.com:Atmosic/apps 
        west update
        #west zephyr-export
        #pip3 install -r zephyr/scripts/requirements.txt
        #pip3 install cryptography
      
    - name: Build Zephyr sample
      run: |
        #export ZEPHYR_SDK_INSTALL_DIR=/home/aerlync/zephyr-sdk-0.16.4
        #source zephyr/zephyr-env.sh
        #Build and Flash
        zephyr/boards/arm/atm33evk/support/run.sh -e -d -w LL -a zephyr/samples/hello_world -j -s 900036560 ATMEVK-3330-QN-5
        #tar -cvf hello_world_sample_ATM33_${TODAY_DATE}.tar build/
        #mv -f hello_world_sample_ATM33_${TODAY_DATE}.tar /home/aerlync/archieve/

    - name: Initiate Python scripts run
      uses: actions/checkout@v3
    - name: Git Tests
      run: |
        git clone https://github.com/sundar-aerlync/Test-aerlync.git
        pip3 install -r requirements.txt
        #source ~/zephyr/.venv/bin/activate
        pytest Tests/Hello_World/test_hello_world_sample.py --port /dev/ttyACM1 --evk ATM3330 --alluredir allure-results/

