name: Zephyr(west) flash and run python test scripts
on: [workflow_dispatch]
#on: [workflow_dispatch]
jobs:
  Zephyrflashandrunscript:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Flash zephyr sample
      #env:
      #  ZEPHYR_BASE: /home/aerlync/zephyr
      #  ZEPHYR_TOOLCHAIN_VARIANT: zephyr
      run: |
        cd /home/aerlync/zephyr
        source ~/zephyr/.venv/bin/activate
        echo source ~/zephyr/.venv/bin/activate      
        echo "Flash sample"
        /home/aerlync/zephyr/zephyr/boards/arm/atm33evk/support/run.sh -e -d -f -w LL -a zephyr/samples/hello_world -j -s 900036560 ATMEVK-3330-QN-5
        #west flash --verify --device=900036560 --jlink --skip-rebuild -d build/ATMEVK-3330-QN-5_ns/zephyr/samples/hello_world --use-elf --elf-file build/ATMEVK-3330-QN-5_ns/zephyr/samples/hello_world/zephyr/zephyr.elf --bin-file build/ATMEVK-3330-QN-5_ns/zephyr/samples/hello_world/zephyr/zephyr.signed.bin --jlink
        
    - name: Initiate Python run
      run: |
        source ~/zephyr/.venv/bin/activate
        pytest ~/zephyr/Aerlync/Tests/BLE -v -s --alluredir allure-results
       
